export const ukrainianAlphabet = [
  { char: "А", answers: ["a"] },
  { char: "Б", answers: ["b"] },
  { char: "В", answers: ["v"] },
  { char: "Г", answers: ["h"] },
  { char: "Ґ", answers: ["g"] },
  { char: "Д", answers: ["d"] },
  { char: "Е", answers: ["e"] },
  { char: "Є", answers: ["ye", "ie"] },
  { char: "Ж", answers: ["zh"] },
  { char: "З", answers: ["z"] },
  { char: "И", answers: ["y"] },
  { char: "І", answers: ["i"] },
  { char: "Ї", answers: ["yi", "i"] },
  { char: "Й", answers: ["y", "j"] },
  { char: "К", answers: ["k"] },
  { char: "Л", answers: ["l"] },
  { char: "М", answers: ["m"] },
  { char: "Н", answers: ["n"] },
  { char: "О", answers: ["o"] },
  { char: "П", answers: ["p"] },
  { char: "Р", answers: ["r"] },
  { char: "С", answers: ["s"] },
  { char: "Т", answers: ["t"] },
  { char: "У", answers: ["u"] },
  { char: "Ф", answers: ["f"] },
  { char: "Х", answers: ["kh", "h"] },
  { char: "Ц", answers: ["ts"] },
  { char: "Ч", answers: ["ch"] },
  { char: "Ш", answers: ["sh"] },
  { char: "Щ", answers: ["shch"] },
  { char: "Ь", answers: ["soft sign", "ь"] },
  { char: "Ю", answers: ["yu", "iu"] },
  { char: "Я", answers: ["ya", "ia"] },
];

export const russianAlphabet = [
  { char: "А", answers: ["a"] },
  { char: "Б", answers: ["b"] },
  { char: "В", answers: ["v"] },
  { char: "Г", answers: ["g"] },
  { char: "Д", answers: ["d"] },
  { char: "Е", answers: ["e", "ye"] },
  { char: "Ё", answers: ["yo", "jo"] },
  { char: "Ж", answers: ["zh"] },
  { char: "З", answers: ["z"] },
  { char: "И", answers: ["i"] },
  { char: "Й", answers: ["y", "j"] },
  { char: "К", answers: ["k"] },
  { char: "Л", answers: ["l"] },
  { char: "М", answers: ["m"] },
  { char: "Н", answers: ["n"] },
  { char: "О", answers: ["o"] },
  { char: "П", answers: ["p"] },
  { char: "Р", answers: ["r"] },
  { char: "С", answers: ["s"] },
  { char: "Т", answers: ["t"] },
  { char: "У", answers: ["u"] },
  { char: "Ф", answers: ["f"] },
  { char: "Х", answers: ["kh", "h"] },
  { char: "Ц", answers: ["ts"] },
  { char: "Ч", answers: ["ch"] },
  { char: "Ш", answers: ["sh"] },
  { char: "Щ", answers: ["shch"] },
  { char: "Ъ", answers: ["hard sign", "ъ"] },
  { char: "Ы", answers: ["y"] },
  { char: "Ь", answers: ["soft sign", "ь"] },
  { char: "Э", answers: ["e"] },
  { char: "Ю", answers: ["yu", "iu"] },
  { char: "Я", answers: ["ya", "ia"] },
];
